AllCops:
  Exclude:
    - 'bin/**'

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false